module.exports.EVENTS = {
  ENTER_CHANNEL: 'enter channel',
  LISTEN_ENTER_CHANNEL: 'listen enter channel',
  CREATE_CHANNEL: 'create channel',
  LISTEN_CREATE_CHANNEL: 'listen create channel',
  EXIT_CHANNEL: 'exit channel',
  LISTEN_EXIT_CHANNEL: 'listen exit channel',
  END_CHANNEL: 'end channel',
  LISTEN_END_CHANNEL: 'listen end channel',
  NEW_CHAT: 'new chat',
  LISTEN_NEW_CHAT: 'listen new chat',
  PLAYER_READY: 'player ready',
  LISTEN_PLAYER_READY: 'listen player ready',
  LISTEN_SEND_SIGNAL: 'listen send signal',
  ALL_USER: 'all user',
  SENDING_SIGNAL: 'sending signal',
  RETURNING_SIGNAL: 'returning signal',
  USER_JOINED: 'user joined',
  RECEIVING_RETURNED_SIGNAL: 'receiving returned signal',
  LISTEN_GAME_START: 'listen game start',
  READY_TO_START: 'start game',
  LISTEN_READY_TO_START: 'listen start game',
};
